### ISSUE TITLE
generateMnemonic should return an array

### ISSUE THREAD

**Issue by ryanleecode** [polkadot-labs/hdkd#104]
This should return an array rather than string IMO. B/c you need to arbitrary assume the delimiter to split, where as if its an array i can easily reverse the operation with `join`.

https://github.com/polkadot-labs/hdkd/blob/fc5b52f9960c0ad8b0bb7397fff0ffe75b58907f/packages/hdkd-helpers/src/bip39.ts#L90

**Comment by kratico** [comment]
A _mnemonic_ is a sentence so returning a `string` is fine.
The definition of a sentence may be words separated/joined by spaces but I couldn't find the sentence definition in the [spec](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#motivation), so this is ambiguous.
Anyway, this is also consistent with `mnemonicToEntropy` and `entropyToMnemonic` types which was ported/adapted from https://github.com/bitcoinjs/bip39/blob/a7ecbfe2e60d0214ce17163d610cad9f7b23140c/ts_src/index.ts

Nevertheless, a few helper functions can be added to return/receive the mnemonic words as an array.
